# Generated by Django 5.1.1 on 2024-09-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь')),
                ('rooms_count', models.CharField(choices=[('STU', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=3, verbose_name='Число комнат')),
                ('wc_count', models.IntegerField(verbose_name='Число санузлов')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('status', models.CharField(choices=[('AVL', 'Доступна'), ('BKD', 'Забронирована'), ('SLD', 'Продана')], default='AVL', max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
