# Generated by Django 5.1.1 on 2024-09-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='rooms_count',
            field=models.IntegerField(choices=[(0, 'Студия'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Число комнат'),
        ),
    ]
