# Generated by Django 5.1.1 on 2024-09-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_floor_remove_flat_floor_flat_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.flat'),
        ),
    ]
