# Generated by Django 5.1.1 on 2024-09-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_flat_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AddField(
            model_name='flat',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.floor'),
        ),
    ]
