# Generated by Django 5.1.1 on 2024-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_alter_floor_options_flat_number_alter_flat_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.IntegerField(default=111, verbose_name='Номер квартиры'),
            preserve_default=False,
        ),
    ]
