# Generated by Django 5.1.1 on 2024-09-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_alter_flat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='flats_count',
            new_name='flats_on_floor',
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.floor', verbose_name='Этаж'),
        ),
    ]
