# Generated by Django 5.1.1 on 2024-10-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_rename_flats_count_floor_flats_on_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('number', models.IntegerField(verbose_name='Номер дома')),
                ('entrances', models.IntegerField(verbose_name='Число подъездов в доме')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('total_buildings', models.IntegerField(verbose_name='Число домов в проекте')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('number', models.IntegerField(verbose_name='Номер подъезда')),
                ('total_flats', models.IntegerField(verbose_name='Общее число квартир')),
                ('total_floors', models.IntegerField(verbose_name='Общее число этажей')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.building', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Подъезд',
                'verbose_name_plural': 'Подъезды',
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='entrance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.entrance', verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.project', verbose_name='Проект'),
        ),
    ]
