# Generated by Django 5.1.1 on 2024-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_building_project_entrance_floor_entrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='commissioning_date',
            field=models.DateField(null=True, verbose_name='Дата сдачи дома'),
        ),
    ]
