# Generated by Django 5.1.1 on 2024-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_building_commissioning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='max_floors',
            field=models.IntegerField(null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.IntegerField(verbose_name='Номер дома (корпуса)'),
        ),
    ]
