# Generated by Django 5.1.1 on 2024-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_building_max_floors_alter_building_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='Город'),
        ),
    ]
