# Generated by Django 5.1.1 on 2024-11-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0012_rename_entrances_building_entrances_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='floor',
            new_name='storey',
        ),
    ]
